// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/webook-project-go/webook-relation/grpc"
	"github.com/webook-project-go/webook-relation/ioc"
	"github.com/webook-project-go/webook-relation/repository"
	"github.com/webook-project-go/webook-relation/repository/cache"
	"github.com/webook-project-go/webook-relation/repository/dao"
	"github.com/webook-project-go/webook-relation/service"
)

// Injectors from wire.go:

func InitApp() *App {
	client := ioc.InitEtcd()
	grpcxServer := ioc.InitGrpcServer(client)
	cmdable := ioc.InitRedis()
	cacheCache := cache.New(cmdable)
	db := ioc.InitDatabase()
	daoDao := dao.New(db)
	repositoryRepository := repository.New(cacheCache, daoDao)
	serviceService := service.New(repositoryRepository)
	grpcService := grpc.New(serviceService)
	app := &App{
		Server:  grpcxServer,
		Service: grpcService,
	}
	return app
}

// wire.go:

var interactiveServiceProvider = wire.NewSet(service.New, repository.New, cache.New, dao.New)

var thirdPartyProvider = wire.NewSet(ioc.InitDatabase, ioc.InitRedis, ioc.InitEtcd)
