grpc:
  server:
    addr: "localhost:40001"
    protocol: "tcp"
mysql:
  dsn: "root:root@tcp(localhost:13316)/webook"

etcd:
  addrs:
    - "localhost:13317"

redis:
  addr: "localhost:13322"
kafka:
  addrs:
    - "localhost:9094"